<?php
// $HeadURL: http://joomlacode.org/svn/joomgallery/JG-1.0/JG/trunk/administrator/components/com_joomgallery/adminexif/admin.exifarray.php $
// $Id: admin.exifarray.php 396 2009-03-15 16:06:21Z aha $
/******************************************************************************\
**   JoomGallery  1.0.1                                                       **
**   By: JoomGallery::ProjectTeam                                             **
**   Copyright (C) 2008  M. Andreas Boettcher                                 **
**   Based on: PonyGallery ML 2.5.1 by PonyGallery-ML-Team                    **
**   Released under GNU GPL Public License                                    **
**   License: http://www.gnu.org/copyleft/gpl.html or have a look             **
**   at administrator/components/com_joomgallery/LICENSE.TXT                  **
\******************************************************************************/

#### Original Copyright ########################################################
## PonyGallery ML 2.5.1                                                       ##
## By: M. Andreas Boettcher & Benjamin Malte Meier                            ##
## & Andreas Hartmann & The ML-Team                                           ##
## Copyright (C) 2007 M. Andreas Boettcher, All rights reserved.              ##
## Released under GNU GPL Public License                                      ##
################################################################################

# Don't allow direct linking
defined( '_VALID_MOS' ) or die( 'Direct Access to this location is not allowed.' );

    $exif_config_array = array
    (
      "IFD0" => array
      (
        270 => array(   'Attribute'   => "ImageDescription",
                        'Name'        => _JGSE_IFD0_IMAGEDESCRIPTION,
                        'Description' => _JGSE_IFD0_IMAGEDESCRIPTION_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
        271 => array(   'Attribute'   => "Make",
                        'Name'        => _JGSE_IFD0_MAKE,
                        'Description' => _JGSE_IFD0_MAKE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
        272 => array(   'Attribute'   => "Model",
                        'Name'        => _JGSE_IFD0_MODEL,
                        'Description' => _JGSE_IFD0_MODEL_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
        274 => array(   'Attribute'   => "Orientation",
                        'Name'        => _JGSE_IFD0_ORIENTATION,
                        'Description' => _JGSE_IFD0_ORIENTATION_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_IFD0_ORIENTATION_1,
                                    2 => _JGSE_IFD0_ORIENTATION_2,
                                    3 => _JGSE_IFD0_ORIENTATION_3,
                                    4 => _JGSE_IFD0_ORIENTATION_4,
                                    5 => _JGSE_IFD0_ORIENTATION_5,
                                    6 => _JGSE_IFD0_ORIENTATION_6,
                                    7 => _JGSE_IFD0_ORIENTATION_7,
                                    8 => _JGSE_IFD0_ORIENTATION_8
                    ),
        282 => array(   'Attribute'   => "XResolution",
                        'Name'        => _JGSE_IFD0_XRESOLUTION,
                        'Description' => _JGSE_IFD0_XRESOLUTION_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_IFD0_DOTSPERRESOLUTIONUNIT
                    ),
        283 => array(   'Attribute'   => "YResolution",
                        'Name'        => _JGSE_IFD0_YRESOLUTION,
                        'Description' => _JGSE_IFD0_YRESOLUTION_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_IFD0_DOTSPERRESOLUTIONUNIT
                    ),
        296 => array(   'Attribute'   => "ResolutionUnit",
                        'Name'        => _JGSE_IFD0_RESOLUTIONUNIT,
                        'Description' => _JGSE_IFD0_RESOLUTIONUNIT_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_IFD0_RESOLUTIONUNIT_1,
                                    2 => _JGSE_IFD0_RESOLUTIONUNIT_2,
                                    3 => _JGSE_IFD0_RESOLUTIONUNIT_3,
                                    4 => _JGSE_IFD0_RESOLUTIONUNIT_4,
                                    5 => _JGSE_IFD0_RESOLUTIONUNIT_5
                    ),
        305 => array(   'Attribute'   => "Software",
                        'Name'        => _JGSE_IFD0_SOFTWARE,
                        'Description' => _JGSE_IFD0_SOFTWARE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
        306 => array(   'Attribute'   => "DateTime",
                        'Name'        => _JGSE_IFD0_DATETIME,
                        'Description' => _JGSE_IFD0_DATETIME_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
        318 => array(   'Attribute'   => "WhitePoint",
                        'Name'        => _JGSE_IFD0_WHITEPOINT,
                        'Description' => _JGSE_IFD0_WHITEPOINT_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
        319 => array(   'Attribute'   => "PrimaryChromaticities",
                        'Name'        => _JGSE_IFD0_PRIMARYCHROMATICITIES,
                        'Description' => _JGSE_IFD0_PRIMARYCHROMATICITIES_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
        529 => array(   'Attribute'   => "YCbCrCoefficients",
                        'Name'        => _JGSE_IFD0_YCBCRCOEFFICIENTS,
                        'Description' => _JGSE_IFD0_YCBCRCOEFFICIENTS_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
        531 => array(   'Attribute'   => "YCbCrPositioning",
                        'Name'        => _JGSE_IFD0_YCBCRPOSITIONING,
                        'Description' => _JGSE_IFD0_YCBCRPOSITIONING_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_IFD0_YCBCRPOSITIONING_1,
                                    2 => _JGSE_IFD0_YCBCRPOSITIONING_2
                    ),
        532 => array(   'Attribute'   => "ReferenceBlackWhite",
                        'Name'        => _JGSE_IFD0_REFERENCEBLACKWHITE, 
                        'Description' => _JGSE_IFD0_REFERENCEBLACKWHITE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
        315 => array(   'Attribute'   => "Artist",
                        'Name'        => _JGSE_IFD0_ARTIST,
                        'Description' => _JGSE_IFD0_ARTIST_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
      33432 => array(   'Attribute'   => "Copyright",
                        'Name'        => _JGSE_IFD0_COPYRIGHT,
                        'Description' => _JGSE_IFD0_COPYRIGHT_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
      ),

      'EXIF' => array 
        (
      33434 => array(   'Attribute'   => "ExposureTime",
                        'Name'        => _JGSE_SUBIFD_EXPOSURETIME,
                        'Description' => _JGSE_SUBIFD_EXPOSURETIME_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SECONDS
                    ),
      33437 => array(   'Attribute'   => "FNumber",
                        'Name'        => _JGSE_SUBIFD_FNUMBER,
                        'Description' => _JGSE_SUBIFD_FNUMBER_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
      34850 => array(   'Attribute'   => "ExposureProgram",
                        'Name'        => _JGSE_SUBIFD_EXPOSUREPROGRAM,
                        'Description' => _JGSE_SUBIFD_EXPOSUREPROGRAM_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_EXPOSUREPROGRAM_0,
                                    1 => _JGSE_SUBIFD_EXPOSUREPROGRAM_1,
                                    2 => _JGSE_SUBIFD_EXPOSUREPROGRAM_2,
                                    3 => _JGSE_SUBIFD_EXPOSUREPROGRAM_3,
                                    4 => _JGSE_SUBIFD_EXPOSUREPROGRAM_4,
                                    5 => _JGSE_SUBIFD_EXPOSUREPROGRAM_5,
                                    6 => _JGSE_SUBIFD_EXPOSUREPROGRAM_6,
                                    7 => _JGSE_SUBIFD_EXPOSUREPROGRAM_7,
                                    8 => _JGSE_SUBIFD_EXPOSUREPROGRAM_8
                    ),
      34855 => array(   'Attribute'   => "ISOSpeedRatings",
                        'Name'        => _JGSE_SUBIFD_ISOSPEEDRATINGS,
                        'Description' => _JGSE_SUBIFD_ISOSPEEDRATINGS_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Short",
                        'Units'       => ""
                    ),
      36864 => array(   'Attribute'   => "ExifVersion",
                        'Name'        => _JGSE_SUBIFD_EXIFVERSION,
                        'Description' => _JGSE_SUBIFD_EXIFVERSION_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Undefined",
                        'Units'       => ""
                    ),
      36867 => array(   'Attribute'   => "DateTimeOriginal",
                        'Name'        => _JGSE_SUBIFD_DATETIMEORIGINAL,
                        'Description' => _JGSE_SUBIFD_DATETIMEORIGINAL_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
      36868 => array(   'Attribute'   => "DateTimeDigitized",
                        'Name'        => _JGSE_SUBIFD_DATETIMEDIGITIZED,
                        'Description' => _JGSE_SUBIFD_DATETIMEDIGITIZED_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
      37121 => array(   'Attribute'   => "ComponentsConfiguration",
                        'Name'        => _JGSE_SUBIFD_COMPONENTSCONFIGURATION,
                        'Description' => _JGSE_SUBIFD_COMPONENTSCONFIGURATION_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Undefined",
                        'Units'       => ""
                    ),
      37122 => array(   'Attribute'   => "CompressedBitsPerPixel",
                        'Name'        => _JGSE_SUBIFD_COMPRESSEDBITSPERPIXEL,
                        'Description' => _JGSE_SUBIFD_COMPRESSEDBITSPERPIXEL_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_COMPRESSEDBITSPERPIXEL_UNIT
                    ),
      37377 => array(   'Attribute'   => "ShutterSpeedValue",
                        'Name'        => _JGSE_SUBIFD_SHUTTERSPEEDVALUE,
                        'Description' => _JGSE_SUBIFD_SHUTTERSPEEDVALUE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Signed Rational",
                        'Units'       => _JGSE_SUBIFD_SHUTTERSPEEDVALUE_UNIT
                    ),
      37378 => array(   'Attribute'   => "ApertureValue",
                        'Name'        => _JGSE_SUBIFD_APERTUREVALUE,
                        'Description' => _JGSE_SUBIFD_APERTUREVALUE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_APERTUREVALUE_UNIT
                    ),
      37379 => array(   'Attribute'   => "BrightnessValue",
                        'Name'        => _JGSE_SUBIFD_BRIGHTNESSVALUE,
                        'Description' => _JGSE_SUBIFD_BRIGHTNESSVALUE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Signed Rational",
                        'Units'       => _JGSE_SUBIFD_BRIGHTNESSVALUE_UNIT
                    ),
      37380 => array(   'Attribute'   => "ExposureBiasValue",
                        'Name'        => _JGSE_SUBIFD_EXPOSUREBIASVALUE,
                        'Description' => _JGSE_SUBIFD_EXPOSUREBIASVALUE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Signed Rational",
                        'Units'       => _JGSE_SUBIFD_EXPOSUREBIASVALUE_UNIT
                    ),
      37381 => array(   'Attribute'   => "MaxApertureValue",
                        'Name'        => _JGSE_SUBIFD_MAXAPERTUREVALUE,
                        'Description' => _JGSE_SUBIFD_MAXAPERTUREVALUE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_APERTUREVALUE_UNIT
                    ),
      37382 => array(   'Attribute'   => "SubjectDistance",
                        'Name'        => _JGSE_SUBIFD_SUBJECTDISTANCE,
                        'Description' => _JGSE_SUBIFD_SUBJECTDISTANCE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Signed Rational",
                        'Units'       => _JGSE_SUBIFD_SUBJECTDISTANCE_UNIT
                    ),
      37383 => array(   'Attribute'   => "MeteringMode",
                        'Name'        => _JGSE_SUBIFD_METERINGMODE,
                        'Description' => _JGSE_SUBIFD_METERINGMODE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_METERINGMODE_0,
                                    1 => _JGSE_SUBIFD_METERINGMODE_1,
                                    2 => _JGSE_SUBIFD_METERINGMODE_2,
                                    3 => _JGSE_SUBIFD_METERINGMODE_3,
                                    4 => _JGSE_SUBIFD_METERINGMODE_4,
                                    5 => _JGSE_SUBIFD_METERINGMODE_5,
                                    6 => _JGSE_SUBIFD_METERINGMODE_6,
                                  255 => _JGSE_SUBIFD_METERINGMODE_255
                    ),
      37384 => array(   'Attribute'   => "LightSource",
                        'Name'        => _JGSE_SUBIFD_LIGHTSOURCE,
                        'Description' => _JGSE_SUBIFD_LIGHTSOURCE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_LIGHTSOURCE_0,
                                    1 => _JGSE_SUBIFD_LIGHTSOURCE_1,
                                    2 => _JGSE_SUBIFD_LIGHTSOURCE_2,
                                    3 => _JGSE_SUBIFD_LIGHTSOURCE_3,
                                    4 => _JGSE_SUBIFD_LIGHTSOURCE_4,
                                    9 => _JGSE_SUBIFD_LIGHTSOURCE_9,
                                   10 => _JGSE_SUBIFD_LIGHTSOURCE_10,
                                   11 => _JGSE_SUBIFD_LIGHTSOURCE_11,
                                   12 => _JGSE_SUBIFD_LIGHTSOURCE_12,
                                   13 => _JGSE_SUBIFD_LIGHTSOURCE_13,
                                   14 => _JGSE_SUBIFD_LIGHTSOURCE_14,
                                   15 => _JGSE_SUBIFD_LIGHTSOURCE_15,
                                   17 => _JGSE_SUBIFD_LIGHTSOURCE_17,
                                   18 => _JGSE_SUBIFD_LIGHTSOURCE_18,
                                   19 => _JGSE_SUBIFD_LIGHTSOURCE_19,
                                   20 => _JGSE_SUBIFD_LIGHTSOURCE_20,
                                   21 => _JGSE_SUBIFD_LIGHTSOURCE_21,
                                   22 => _JGSE_SUBIFD_LIGHTSOURCE_22,
                                   23 => _JGSE_SUBIFD_LIGHTSOURCE_23,
                                   24 => _JGSE_SUBIFD_LIGHTSOURCE_24,
                                  255 => _JGSE_SUBIFD_LIGHTSOURCE_255
                    ),
      37385 => array(   'Attribute'   => "Flash",
                        'Name'        => _JGSE_SUBIFD_FLASH,
                        'Description' => _JGSE_SUBIFD_FLASH_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_FLASH_0,
                                    1 => _JGSE_SUBIFD_FLASH_1,
                                    5 => _JGSE_SUBIFD_FLASH_5,
                                    7 => _JGSE_SUBIFD_FLASH_7,
                                    8 => _JGSE_SUBIFD_FLASH_8,
                                    9 => _JGSE_SUBIFD_FLASH_9,
                                   13 => _JGSE_SUBIFD_FLASH_13,
                                   15 => _JGSE_SUBIFD_FLASH_15,
                                   16 => _JGSE_SUBIFD_FLASH_16,
                                   20 => _JGSE_SUBIFD_FLASH_20,
                                   24 => _JGSE_SUBIFD_FLASH_24,
                                   25 => _JGSE_SUBIFD_FLASH_25,
                                   29 => _JGSE_SUBIFD_FLASH_29,
                                   31 => _JGSE_SUBIFD_FLASH_31,
                                   32 => _JGSE_SUBIFD_FLASH_32,
                                   48 => _JGSE_SUBIFD_FLASH_48,
                                   65 => _JGSE_SUBIFD_FLASH_65,
                                   69 => _JGSE_SUBIFD_FLASH_69,
                                   71 => _JGSE_SUBIFD_FLASH_71,
                                   73 => _JGSE_SUBIFD_FLASH_73,
                                   77 => _JGSE_SUBIFD_FLASH_77,
                                   79 => _JGSE_SUBIFD_FLASH_79,
                                   80 => _JGSE_SUBIFD_FLASH_80,
                                   88 => _JGSE_SUBIFD_FLASH_88,
                                   89 => _JGSE_SUBIFD_FLASH_89,
                                   93 => _JGSE_SUBIFD_FLASH_93,
                                   95 => _JGSE_SUBIFD_FLASH_95
                    ),
      37386 => array(   'Attribute'   => "FocalLength",
                        'Name'        => _JGSE_SUBIFD_FOCALLENGTH,
                        'Description' => _JGSE_SUBIFD_FOCALLENGTH_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_FOCALLENGTH_UNIT
                    ),
//       37510 => array(   'Attribute'   => "UserComment",
//                         'Name'        => _JGSE_SUBIFD_USERCOMMENT,
//                         'Description' => _JGSE_SUBIFD_USERCOMMENT_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "Undefined",
//                         'Units'       => ""
//                     ),
//       37520 => array(   'Attribute'   => "SubsecTime",
//                         'Name'        => _JGSE_SUBIFD_SUBSECTIME,
//                         'Description' => _JGSE_SUBIFD_SUBSECTIME_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "ASCII String",
//                         'Units'       => ""
//                     ),
//       37521 => array(   'Attribute'   => "SubsecTimeOriginal",
//                         'Name'        => _JGSE_SUBIFD_SUBSECTIMEORIGINAL,
//                         'Description' => _JGSE_SUBIFD_SUBSECTIMEORIGINAL_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "ASCII String",
//                         'Units'       => ""
//                     ),
//       37522 => array(   'Attribute'   => "SubsecTimeDigitized",
//                         'Name'        => _JGSE_SUBIFD_SUBSECTIMEDIGITIZED,
//                         'Description' => _JGSE_SUBIFD_SUBSECTIMEDIGITIZED_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "ASCII String",
//                         'Units'       => ""
//                     ),
//       40960 => array(   'Attribute'   => "FlashPixVersion",
//                         'Name'        => _JGSE_SUBIFD_FLASHPIXVERSION,
//                         'Description' => _JGSE_SUBIFD_FLASHPIXVERSION_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "Undefined",
//                         'Units'       => ""
//                     ),
      40961 => array(   'Attribute'   => "ColorSpace",
                        'Name'        => _JGSE_SUBIFD_COLORSPACE,
                        'Description' => _JGSE_SUBIFD_COLORSPACE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_SUBIFD_COLORSPACE_SRGB,
                                65535 => _JGSE_SUBIFD_COLORSPACE_65535
                    ),
      40962 => array(   'Attribute'   => "ExifImageWidth",
                        'Name'        => _JGSE_SUBIFD_EXIFIMAGEWIDTH,
                        'Description' => _JGSE_SUBIFD_EXIFIMAGEWIDTH_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Short/Long",
                        'Units'       => _JGSE_SUBIFD_EXIFIMAGEWIDTHLENGTH_UNIT
                    ),
      40963 => array(   'Attribute'   => "ExifImageLength",
                        'Name'        => _JGSE_SUBIFD_EXIFIMAGELENGTH,
                        'Description' => _JGSE_SUBIFD_EXIFIMAGELENGTH_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Short/Long",
                        'Units'       => _JGSE_SUBIFD_EXIFIMAGEWIDTHLENGTH_UNIT
                    ),
//       40964 => array(   'Attribute'   => "RelatedSoundFile",
//                         'Name'        => _JGSE_SUBIFD_RELATEDSOUNDFILE,
//                         'Description' => _JGSE_SUBIFD_RELATEDSOUNDFILE_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "ASCII String",
//                         'Units'       => ""
//                     ),
//       40965 => array(   'Attribute'   => "ExifInteroperabilityOffset",
//                         'Name'        => _JGSE_SUBIFD_EXIFINTEROPERABILITYOFFSET,
//                         'Description' => _JGSE_SUBIFD_EXIFINTEROPERABILITYOFFSET_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "Unsigned Long",
//                         'Units'       => ""
//                     ),
      41486 => array(   'Attribute'   => "FocalPlaneXResolution",
                        'Name'        => _JGSE_SUBIFD_FOCALPLANEXRESOLUTION,
                        'Description' => _JGSE_SUBIFD_FOCALPLANEXRESOLUTION_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_FOCALPLANEXYRESOLUTION_UNIT
                    ),
      41487 => array(   'Attribute'   => "FocalPlaneYResolution",
                        'Name'        => _JGSE_SUBIFD_FOCALPLANEYRESOLUTION,
                        'Description' => _JGSE_SUBIFD_FOCALPLANEYRESOLUTION_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_SUBIFD_FOCALPLANEXYRESOLUTION_UNIT
                    ),
      41488 => array(   'Attribute'   => "FocalPlaneResolutionUnit",
                        'Name'        => _JGSE_SUBIFD_FOCALPLANERESOLUTIONUNIT,
                        'Description' => _JGSE_SUBIFD_FOCALPLANERESOLUTIONUNIT_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_SUBIFD_FOCALPLANERESOLUTIONUNIT_1,
                                    2 => _JGSE_SUBIFD_FOCALPLANERESOLUTIONUNIT_2,
                                    3 => _JGSE_SUBIFD_FOCALPLANERESOLUTIONUNIT_3
                    ),
      41493 => array(   'Attribute'   => "ExposureIndex",
                        'Name'        => _JGSE_SUBIFD_EXPOSUREINDEX,
                        'Description' => _JGSE_SUBIFD_EXPOSUREINDEX_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
      41495 => array(   'Attribute'   => "SensingMethod",
                        'Name'        => _JGSE_SUBIFD_SENSINGMETHOD,
                        'Description' => _JGSE_SUBIFD_SENSINGMETHOD_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    1 => _JGSE_SUBIFD_SENSINGMETHOD_1,
                                    2 => _JGSE_SUBIFD_SENSINGMETHOD_2,
                                    3 => _JGSE_SUBIFD_SENSINGMETHOD_3,
                                    4 => _JGSE_SUBIFD_SENSINGMETHOD_4,
                                    5 => _JGSE_SUBIFD_SENSINGMETHOD_5,
                                    7 => _JGSE_SUBIFD_SENSINGMETHOD_7,
                                    8 => _JGSE_SUBIFD_SENSINGMETHOD_8
                    ),
      41728 => array(   'Attribute'   => "FileSource",
                        'Name'        => _JGSE_SUBIFD_FILESOURCE,
                        'Description' => _JGSE_SUBIFD_FILESOURCE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Undefined",
                        'Units'       => "",
                                    3 => _JGSE_SUBIFD_FILESOURCE_3
                    ),
      41729 => array(   'Attribute'   => "SceneType",
                        'Name'        => _JGSE_SUBIFD_SCENETYPE,
                        'Description' => _JGSE_SUBIFD_SCENETYPE_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Undefined",
                        'Units'       => "",
                                    1 => _JGSE_SUBIFD_SCENETYPE_1
                    ),
      41986 => array(   'Attribute'   => "ExposureMode",
                        'Name'        => _JGSE_SUBIFD_EXPOSUREMODE,
                        'Description' => _JGSE_SUBIFD_EXPOSUREMODE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_EXPOSUREMODE_0,
                                    1 => _JGSE_SUBIFD_EXPOSUREMODE_1,
                                    2 => _JGSE_SUBIFD_EXPOSUREMODE_2
                    ),
      41987 => array(   'Attribute'   => "WhiteBalance",
                        'Name'        => _JGSE_SUBIFD_WHITEBALANCE,
                        'Description' => _JGSE_SUBIFD_WHITEBALANCE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_WHITEBALANCE_0,
                                    1 => _JGSE_SUBIFD_WHITEBALANCE_1
                    ),
      41988 => array(   'Attribute'   => "DigitalZoomRatio",
                        'Name'        => _JGSE_SUBIFD_DIGITALZOOMRATIO,
                        'Description' => _JGSE_SUBIFD_DIGITALZOOMRATIO_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
      41989 => array(   'Attribute'   => "FocalLengthIn35mmFilm",
                        'Name'        => _JGSE_SUBIFD_FOCALLENGTHIN35MMFILM,
                        'Description' => _JGSE_SUBIFD_FOCALLENGTHIN35MMFILM_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Unsigned Short",
                        'Units'       => _JGSE_SUBIFD_FOCALLENGTHIN35MMFILM_UNIT
                    ),
      41990 => array(   'Attribute'   => "SceneCaptureType",
                        'Name'        => _JGSE_SUBIFD_SCENECAPTURETYPE,
                        'Description' => _JGSE_SUBIFD_SCENECAPTURETYPE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_SCENECAPTURETYPE_0,
                                    1 => _JGSE_SUBIFD_SCENECAPTURETYPE_1,
                                    2 => _JGSE_SUBIFD_SCENECAPTURETYPE_2,
                                    3 => _JGSE_SUBIFD_SCENECAPTURETYPE_3
                    ),
      41991 => array(   'Attribute'   => "GainControl",
                        'Name'        => _JGSE_SUBIFD_GAINCONTROL,
                        'Description' => _JGSE_SUBIFD_GAINCONTROL_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Rational",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_GAINCONTROL_0,
                                    1 => _JGSE_SUBIFD_GAINCONTROL_1,
                                    2 => _JGSE_SUBIFD_GAINCONTROL_2,
                                    3 => _JGSE_SUBIFD_GAINCONTROL_3,
                                    4 => _JGSE_SUBIFD_GAINCONTROL_4
                    ),
      41992 => array(   'Attribute'   => "Contrast",
                        'Name'        => _JGSE_SUBIFD_CONTRAST,
                        'Description' => _JGSE_SUBIFD_CONTRAST_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_CONTRAST_0,
                                    1 => _JGSE_SUBIFD_CONTRAST_1,
                                    2 => _JGSE_SUBIFD_CONTRAST_2
                    ),
      41993 => array(   'Attribute'   => "Saturation",
                        'Name'        => _JGSE_SUBIFD_SATURATION,
                        'Description' => _JGSE_SUBIFD_SATURATION_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_SATURATION_0,
                                    1 => _JGSE_SUBIFD_SATURATION_1,
                                    2 => _JGSE_SUBIFD_SATURATION_2
                    ),
      41994 => array(   'Attribute'   => "Sharpness",
                        'Name'        => _JGSE_SUBIFD_SHARPNESS,
                        'Description' => _JGSE_SUBIFD_SHARPNESS_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_SHARPNESS_0,
                                    1 => _JGSE_SUBIFD_SHARPNESS_1,
                                    2 => _JGSE_SUBIFD_SHARPNESS_2
                    ),
//       41995 => array(   'Attribute'   => "DeviceSettingDescription",
//                         'Name'        => _JGSE_SUBIFD_DEVICESETTINGDESCRIPTION,
//                         'Description' => _JGSE_SUBIFD_DEVICESETTINGDESCRIPTION_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "Undefined",
//                         'Units'       => ""
//                     ),
      41996 => array(   'Attribute'   => "SubjectDistanceRange",
                        'Name'        => _JGSE_SUBIFD_SUBJECTDISTANCERANGE,
                        'Description' => _JGSE_SUBIFD_SUBJECTDISTANCERANGE_DESCRIPTION,
                        'Calculation' => "Array",
                        'Format'      => "Unsigned Short",
                        'Units'       => "",
                                    0 => _JGSE_SUBIFD_SUBJECTDISTANCERANGE_0,
                                    1 => _JGSE_SUBIFD_SUBJECTDISTANCERANGE_1,
                                    2 => _JGSE_SUBIFD_SUBJECTDISTANCERANGE_2,
                                    3 => _JGSE_SUBIFD_SUBJECTDISTANCERANGE_3
                    ),
//       42016 => array(   'Attribute'   => "ImageUniqueID",
//                         'Name'        => _JGSE_SUBIFD_IMAGEUNIQUEID,
//                         'Description' => _JGSE_SUBIFD_IMAGEUNIQUEID_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "",
//                         'Units'       => ""
//                     )
      ),

      "GPS" => array(
//           0 => array(   'Attribute'   => "GPSVersionID",
//                         'Name'        => _JGSE_GPS_GPSVERSIONID,
//                         'Description' => _JGSE_GPS_GPSVERSIONID_DESCRIPTION,
//                         'Calculation' => "",
//                         'Format'      => "Byte",
//                         'Units'       => ""
//                     ),
          1 => array(   'Attribute'   => "GPSLatitudeRef",
                        'Name'        => _JGSE_GPS_GPSLATITUDEREF,
                        'Description' => _JGSE_GPS_GPSLATITUDEREF_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
          2 => array(   'Attribute'   => "GPSLatitude",
                        'Name'        => _JGSE_GPS_GPSLATITUDE,
                        'Description' => _JGSE_GPS_GPSLATITUDE_DESCRIPTION,
                        'Calculation' => "DegMinSec",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
          3 => array(   'Attribute'   => "GPSLongitudeRef",
                        'Name'        => _JGSE_GPS_GPSLONGITUDEREF,
                        'Description' => _JGSE_GPS_GPSLONGITUDEREF_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "ASCII String",
                        'Units'       => ""
                    ),
          4 => array(   'Attribute'   => "GPSLongitude",
                        'Name'        => _JGSE_GPS_GPSLONGITUDE,
                        'Description' => _JGSE_GPS_GPSLONGITUDE_DESCRIPTION,
                        'Calculation' => "DegMinSec",
                        'Format'      => "Unsigned Rational",
                        'Units'       => ""
                    ),
          5 => array(   'Attribute'   => "GPSAltitudeRef",
                        'Name'        => _JGSE_GPS_GPSALTITUDEREF,
                        'Description' => _JGSE_GPS_GPSALTITUDEREF_DESCRIPTION,
                        'Calculation' => "",
                        'Format'      => "Byte",
                        'Units'       => ""
                    ),
          6 => array(   'Attribute'   => "GPSAltitude",
                        'Name'        => _JGSE_GPS_GPSALTITUDE,
                        'Description' => _JGSE_GPS_GPSALTITUDE_DESCRIPTION,
                        'Calculation' => "Denum",
                        'Format'      => "Unsigned Rational",
                        'Units'       => _JGSE_GPS_GPSALTITUDE_UNIT
                    ),
      ),

    );



?>
